name: analysis

permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *' 
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter requests pandas plotly nltk scikit-learn contractions emoji spacy tldextract seaborn wordcloud
    - name: Download spaCy model
      run: python -m spacy download en_core_web_lg

    - name: Run analysis every 12 hours
      run: jupyter nbconvert --to notebook --execute "eda_ronald.ipynb" --stdout

    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git pull --rebase
        git push --force

