name: latest_analysis.yml

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["request"]
    types:
      - completed
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Clone the SearchTube repo
        run: git clone https://github.com/kcinbk/SearchTube.git

      - name: Include the SearchTube module to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/SearchTube" >> $GITHUB_ENV

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install all necessary packages
        run: |
          pip install --no-cache-dir jupyter requests pandas plotly nltk scikit-learn contractions emoji spacy tldextract seaborn wordcloud google-api-python-client
          pip install git+https://github.com/theskumar/python-dotenv.git#egg=python-dotenv
          pip install git+https://github.com/kcinbk/SearchTube.git#egg=SearchTube
      
          - name: Check TORCH_CACHE Value
          run: echo "TORCH_CACHE is set to '$TORCH_CACHE'"
  
      - name: Set Torch Cache
        run: |
          export TORCH_CACHE=${TORCH_CACHE:-/tmp/torch_cache}
          echo "Using cache directory: $TORCH_CACHE"

      - name: Install PyTorch
        run: |
          export TORCH_CACHE=${TORCH_CACHE:-/tmp/torch_cache}
          pip install -U --cache-dir $TORCH_CACHE torch==2.0.1+cu121 --index-url https://download.pytorch.org/whl/cu121

      - name: Install transformers
        run: |
            git clone https://github.com/huggingface/transformers
            cd transformers
            # if needed switch to the last known good SHA until transformers@master is fixed
            git checkout e7e9261a2
            git rev-parse --short HEAD
            pip install .

      - name: Download spaCy model
        run: python -m spacy download en_core_web_lg

      - name: Run latest_analysis.yml
        run: |
          jupyter nbconvert --to notebook --execute "eda_ronald.ipynb" --stdout || exit 0

      - name: Commit and push any changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git pull --rebase || exit 0
          git push --force || exit 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
