name: request
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install requests pandas 
      - name: Run the request_ronald script
        run: python request_ronald.ipynb
      - name: Convert Jupyter notebook to Python script
      run: |
        jupyter nbconvert --to script request_ronald.ipynb
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
