name: request

permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install all necessary packages
      run: pip install jupyter requests pandas 
    - name: Scraping today's data
      run: jupyter nbconvert --to notebook --execute "request_ronald.ipynb" --stdout
    - name: Commit and push any changes
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
